
### 无过滤条件

GET localhost/api/list/



### 分页

GET localhost/api/list/?_limit=10&_offset=10



### 排序，需要设置 tag: `filter:"order"`
### 字段前加 "-" 表示降序

GET localhost/api/list/?_order=age



### 搜索，需要设置 tag 才能按此字段搜索: `filter:"search"`
### _search_fields 指定搜索字段, 没有设置 search tag 的字段会被忽略
### _search 指定搜索关键字

GET localhost/api/list/?_search_fields=name,email&_search=tom&age=22



### 不指定 _search_fields 则搜索所有配置了 seach tag 的字段

GET localhost/api/list/?_search=tom



### 指定返回字段

GET localhost/api/list/?_fields=name,age



### 按字段过滤，需要设置 match tag: `filter:"match"`

GET localhost/api/list/?name=tom


###

GET localhost/api/list?_limit=10&_order=-age&_search_fields=name&_search=tom

###


